export const BIBLE_BOOKS = [
  { id: 1, name: 'Genesis', aliases: ['genesis', 'gen'] },
  { id: 2, name: 'Exodus', aliases: ['exodus', 'exo', 'exod', 'ex'] },
  { id: 3, name: 'Leviticus', aliases: ['leviticus', 'lev', 'le'] },
  { id: 4, name: 'Numbers', aliases: ['numbers', 'num', 'nums', 'nu', 'nm', 'nb'] },
  { id: 5, name: 'Deuteronomy', aliases: ['deuteronomy', 'deut', 'deu', 'dt'] },
  { id: 6, name: 'Joshua', aliases: ['joshua', 'josh', 'jos'] },
  { id: 7, name: 'Judges', aliases: ['judges', 'judg', 'jdg', 'jg', 'jdgs'] },
  { id: 8, name: 'Ruth', aliases: ['ruth', 'rth', 'ru'] },
  { id: 9, name: '1 Samuel', aliases: ['1 samuel', '1 sam', '1sam', 'i samuel', 'i sam', 'first samuel', 'first sam'] },
  { id: 10, name: '2 Samuel', aliases: ['2 samuel', '2 sam', '2sam', 'ii samuel', 'ii sam', 'second samuel', 'second sam'] },
  { id: 11, name: '1 Kings', aliases: ['1 kings', '1 kgs', '1kgs', '1 kin', '1kin', 'i kings', 'i kgs', 'first kings', 'first kgs'] },
  { id: 12, name: '2 Kings', aliases: ['2 kings', '2 kgs', '2kgs', '2 kin', '2kin', 'ii kings', 'ii kgs', 'second kings', 'second kgs'] },
  { id: 13, name: '1 Chronicles', aliases: ['1 chronicles', '1 chron', '1chr', '1 chr', 'i chronicles', 'i chron', 'first chronicles', 'first chron'] },
  { id: 14, name: '2 Chronicles', aliases: ['2 chronicles', '2 chron', '2chr', '2 chr', 'ii chronicles', 'ii chron', 'second chronicles', 'second chron'] },
  { id: 15, name: 'Ezra', aliases: ['ezra', 'ezr'] },
  { id: 16, name: 'Nehemiah', aliases: ['nehemiah', 'neh', 'ne'] },
  { id: 17, name: 'Esther', aliases: ['esther', 'esth', 'est'] },
  { id: 18, name: 'Job', aliases: ['job'] },
  { id: 19, name: 'Psalms', aliases: ['psalms', 'psalm', 'ps', 'psa', 'psm', 'pss'] },
  { id: 20, name: 'Proverbs', aliases: ['proverbs', 'proverbs', 'prov', 'pro', 'prv', 'pr'] },
  { id: 21, name: 'Ecclesiastes', aliases: ['ecclesiastes', 'eccles', 'eccle', 'ecc', 'ec', 'qoh'] },
  { id: 22, name: 'Song of Solomon', aliases: ['song of solomon', 'song of songs', 'songs', 'song', 'sos', 'canticles', 'song of sol'] },
  { id: 23, name: 'Isaiah', aliases: ['isaiah', 'isa', 'is'] },
  { id: 24, name: 'Jeremiah', aliases: ['jeremiah', 'jer', 'je', 'jr'] },
  { id: 25, name: 'Lamentations', aliases: ['lamentations', 'lam', 'la'] },
  { id: 26, name: 'Ezekiel', aliases: ['ezekiel', 'ezek', 'eze', 'ezk'] },
  { id: 27, name: 'Daniel', aliases: ['daniel', 'dan', 'da', 'dn'] },
  { id: 28, name: 'Hosea', aliases: ['hosea', 'hos', 'ho'] },
  { id: 29, name: 'Joel', aliases: ['joel', 'jl'] },
  { id: 30, name: 'Amos', aliases: ['amos', 'am'] },
  { id: 31, name: 'Obadiah', aliases: ['obadiah', 'obad', 'ob'] },
  { id: 32, name: 'Jonah', aliases: ['jonah', 'jon', 'jnh'] },
  { id: 33, name: 'Micah', aliases: ['micah', 'mic', 'mc'] },
  { id: 34, name: 'Nahum', aliases: ['nahum', 'nah', 'na'] },
  { id: 35, name: 'Habakkuk', aliases: ['habakkuk', 'hab', 'hb'] },
  { id: 36, name: 'Zephaniah', aliases: ['zephaniah', 'zeph', 'zep', 'zp'] },
  { id: 37, name: 'Haggai', aliases: ['haggai', 'hag', 'hg'] },
  { id: 38, name: 'Zechariah', aliases: ['zechariah', 'zech', 'zec', 'zc'] },
  { id: 39, name: 'Malachi', aliases: ['malachi', 'mal', 'ml'] },
  { id: 40, name: 'Matthew', aliases: ['matthew', 'matt', 'mt'] },
  { id: 41, name: 'Mark', aliases: ['mark', 'mrk', 'mk', 'mr'] },
  { id: 42, name: 'Luke', aliases: ['luke', 'luk', 'lk'] },
  { id: 43, name: 'John', aliases: ['john', 'jn', 'jhn'] },
  { id: 44, name: 'Acts', aliases: ['acts', 'act', 'ac'] },
  { id: 45, name: 'Romans', aliases: ['romans', 'rom', 'ro', 'rm'] },
  { id: 46, name: '1 Corinthians', aliases: ['1 corinthians', '1 cor', '1cor', 'i corinthians', 'i cor', 'first corinthians', 'first cor'] },
  { id: 47, name: '2 Corinthians', aliases: ['2 corinthians', '2 cor', '2cor', 'ii corinthians', 'ii cor', 'second corinthians', 'second cor'] },
  { id: 48, name: 'Galatians', aliases: ['galatians', 'gal', 'ga'] },
  { id: 49, name: 'Ephesians', aliases: ['ephesians', 'eph', 'ep'] },
  { id: 50, name: 'Philippians', aliases: ['philippians', 'phil', 'php', 'pp'] },
  { id: 51, name: 'Colossians', aliases: ['colossians', 'col', 'co'] },
  { id: 52, name: '1 Thessalonians', aliases: ['1 thessalonians', '1 thess', '1thess', '1 thes', 'i thessalonians', 'i thess', 'first thessalonians', 'first thess'] },
  { id: 53, name: '2 Thessalonians', aliases: ['2 thessalonians', '2 thess', '2thess', '2 thes', 'ii thessalonians', 'ii thess', 'second thessalonians', 'second thess'] },
  { id: 54, name: '1 Timothy', aliases: ['1 timothy', '1 tim', '1tim', 'i timothy', 'i tim', 'first timothy', 'first tim'] },
  { id: 55, name: '2 Timothy', aliases: ['2 timothy', '2 tim', '2tim', 'ii timothy', 'ii tim', 'second timothy', 'second tim'] },
  { id: 56, name: 'Titus', aliases: ['titus', 'tit', 'ti'] },
  { id: 57, name: 'Philemon', aliases: ['philemon', 'philem', 'phm', 'pm'] },
  { id: 58, name: 'Hebrews', aliases: ['hebrews', 'heb'] },
  { id: 59, name: 'James', aliases: ['james', 'jas', 'jm'] },
  { id: 60, name: '1 Peter', aliases: ['1 peter', '1 pet', '1pet', 'i peter', 'i pet', 'first peter', 'first pet'] },
  { id: 61, name: '2 Peter', aliases: ['2 peter', '2 pet', '2pet', 'ii peter', 'ii pet', 'second peter', 'second pet'] },
  { id: 62, name: '1 John', aliases: ['1 john', '1 jn', '1jn', 'i john', 'i jn', 'first john', 'first jn'] },
  { id: 63, name: '2 John', aliases: ['2 john', '2 jn', '2jn', 'ii john', 'ii jn', 'second john', 'second jn'] },
  { id: 64, name: '3 John', aliases: ['3 john', '3 jn', '3jn', 'iii john', 'iii jn', 'third john', 'third jn'] },
  { id: 65, name: 'Jude', aliases: ['jude', 'jud'] },
  { id: 66, name: 'Revelation', aliases: ['revelation', 'rev', 're', 'the revelation'] },
];

export const SINGLE_CHAPTER_BOOK_IDS = new Set([31, 57, 63, 64, 65]);
